version: '3'

services:

  postgres_db:
    build:
      context: ./db/postgres
    restart: always
    environment:
      POSTGRES_USER: heartistry
      POSTGRES_PASSWORD: heartistry
      POSTGRES_DB: heartistry
    container_name: postgres_db
    networks:
      custom_network:
        ipv4_address: 192.168.1.4
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./heartistry-user-api
    depends_on:
      - postgres_db
    container_name: auth-service
    ports: 
      - "3000:3000"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=192.168.1.4
      - DB_PORT=5432
      - DB_USERNAME=heartistry
      - DB_PASSWORD=heartistry
      - DB_NAME=heartistry
      - DATABASE_URL=postgres://heartistry:heartistry@postgres_db:5432/heartistry
      - JWT_SECRET=c66077ac1510b83fbda3822b8007fafb9fdf6e550d13574bfd98164d0328261e
      - TOKEN_EXPIRE_TIME=24h
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USER=heartistry.service@gmail.com
      - MAIL_PASSWORD=buevjbrngdzaobip
      - MAIL_FROM=noreply@heartistry.com
      - MAIL_PORT=465
      - MAIL_SECURE=465
    networks:
      custom_network:
        ipv4_address: 192.168.1.3

volumes:
  pg-data:

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
