services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/certs
    depends_on:
      - user-service
      - task-service
    networks:
      - overlay_network
    deploy:
      restart_policy:
        condition: on-failure

  postgres_db:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=heartistry
      - POSTGRES_PASSWORD=heartistry
      - POSTGRES_DB=heartistry
    container_name: postgres_db
    networks:
      - overlay_network
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

  user-service:
    build: user-service
    depends_on:
      - postgres_db
    container_name: user-service
    ports: 
      - "3030:3030"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USERNAME=heartistry
      - DB_PASSWORD=heartistry
      - DB_NAME=heartistry
      - DATABASE_URL=postgres://heartistry:heartistry@postgres_db:5432/heartistry
      - JWT_SECRET=c66077ac1510b83fbda3822b8007fafb9fdf6e550d13574bfd98164d0328261e
      - TOKEN_EXPIRE_TIME=24h
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USER=heartistry.service@gmail.com
      - MAIL_PASSWORD=buevjbrngdzaobip
      - MAIL_FROM=noreply@heartistry.com
    networks:
      - overlay_network
    deploy:
      restart_policy:
        condition: on-failure

  mysql_db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=heartistry
      - MYSQL_PASSWORD=heartistry
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=heartistry
    container_name: mysql_db
    networks:
      - overlay_network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure

  task-service:
    build: task-service
    depends_on:
      - mysql_db
    container_name: task-service
    ports:
      - "8000:8000"
    environment:
      - SPRING_APPLICATION_NAME=heartistry-task-api
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/heartistry
      - SPRING_DATASOURCE_USERNAME=heartistry
      - SPRING_DATASOURCE_PASSWORD=heartistry
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui.html
      - JWT_SECRET=c66077ac1510b83fbda3822b8007fafb9fdf6e550d13574bfd98164d0328261e
      - SERVER_PORT=8000
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENDPOINT=/actuator/prometheus
      - MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED=true
      - MANAGEMENT_METRICS_TAGS_APPLICATION=heartistry-task-api
    networks:
      - overlay_network
    deploy:
      restart_policy:
        condition: on-failure



volumes:
  pg-data:
  mysql-data:



networks:
  overlay_network:
    driver: bridge