services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/certs
    depends_on:
      - user-service
      - task-service
    networks:
      - bridge_network
    deploy:
      restart_policy:
        condition: on-failure

  postgres_db:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    container_name: postgres_db
    networks:
      - bridge_network
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure

  user-service:
    build: user-service
    depends_on:
      - postgres_db
    container_name: user-service
    ports: 
      - "3030:3030"
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_EXPIRE_TIME=24h
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
    networks:
      - bridge_network
    deploy:
      restart_policy:
        condition: on-failure

  mysql_db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    container_name: mysql_db
    networks:
      - bridge_network
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure

  task-service:
    build: task-service
    depends_on:
      - mysql_db
    container_name: task-service
    ports:
      - "8000:8000"
    environment:
      - SPRING_APPLICATION_NAME=heartistry-task-api
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui.html
      - JWT_SECRET=c66077ac1510b83fbda3822b8007fafb9fdf6e550d13574bfd98164d0328261e
      - SERVER_PORT=8000
    networks:
      - bridge_network
    deploy:
      restart_policy:
        condition: on-failure



volumes:
  pg-data:
  mysql-data:



networks:
  bridge_network:
    driver: bridge
