{
 "title": "API Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "api_name", "label": "Select an API: ", "query": { "query": "label_values(api_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Error budget remaining",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "job:error_budget:remaining{api_name=~\"$api_name\"}",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "description": "Error rate: across all upstream services [request / s]\nRatio error / request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "task:http_response_error_rate{api_name=~\"$api_name\"}",
     "legendFormat": "{{api_name}} error rate [request / s]"
    },
    {
     "expr": "job:slo_errors_per_request:ratio_rate10m{api_name=~\"$api_name\"}*100",
     "legendFormat": "{{api_name}} ratio error / request [%]"
    }
   ]
  },
  {
   "title": "Upstream time",
   "type": "timeseries",
   "description": "90th, 95th and 99th percentile in [ms]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(tyk_http_latency_bucket{api_name=~\"$api_name\"}[1m])) by (le,api_name))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tyk_http_latency_bucket{api_name=~\"$api_name\"}[1m])) by (le,api_name))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tyk_http_latency_bucket{api_name=~\"$api_name\"}[1m])) by (le,api_name))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "piechart",
   "description": "HTTP status codes returned by upstream services [request / s]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(tyk_http_requests_total{api_name=~\"$api_name\"}[1m])) by (response_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per path",
   "type": "timeseries",
   "description": "[requests / s]",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum (rate(tyk_http_requests_total{api_name=~\"$api_name\"}[1m])) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per method",
   "type": "timeseries",
   "description": "[requests / s]",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum (rate(tyk_http_requests_total{api_name=~\"$api_name\"}[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}