services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile  # Reference to the Dockerfile
    container_name: tyk-redis
    ports:
      - "6379:6379"  # Map the port to the host machine
    networks:
      - tyk
    restart: always

  tyk_gateway:
    build:
      context: ./ # The directory where the Dockerfile is located
    container_name: tyk_gateway
    ports:
      - "8080:8080"  # Map port 8080 on the host to 8080 on the container
    networks:
      - tyk
    volumes:
      - ./tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
    restart: always

networks:
  tyk:
    driver: bridge
