global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  - job_name: "task-service"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["task-service:8000"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "mysql_exporter"
    static_configs:
      - targets: ["mysql_exporter:9104"]