global:
  scrape_interval: 15s  # Chu kỳ thu thập số liệu (mặc định là 15 giây)
  evaluation_interval: 15s  # Chu kỳ đánh giá các cảnh báo (rules)

scrape_configs:
  - job_name: 'nestjs-backend'
    static_configs:
      - targets: ['nestjs-service:3000']  # Endpoint của dịch vụ NestJS

  - job_name: 'springboot-backend'
    static_configs:
      - targets: ['springboot-service:8080']  # Endpoint của dịch vụ Spring Boot

  - job_name: 'mysql-metrics'
    static_configs:
      - targets: ['mysql-exporter:9104']  # Metrics từ MySQL Exporter

  - job_name: 'postgresql-metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']  # Metrics từ PostgreSQL Exporter

