global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "heartistry-task-api"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["task-service:8000"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "mysql_exporter"
    static_configs:
      - targets: ["mysql_exporter:9104"]

  - job_name: "tyk-api-gateway"
    static_configs:
      - targets: ['host.docker.internal:8084']