# Use the official Redis image as a base
FROM redis:4.0-alpine

# Expose the Redis port
EXPOSE 6379

# The default command is already set in the Redis image
# So we don't need to specify anything further
